export interface IEpic {
    assigned_to?: null;
    assigned_to_extra_info?: null;
    attachments?: (null)[] | null;
    blocked_note: string;
    blocked_note_html: string;
    client_requirement: boolean;
    color: string;
    comment: string;
    created_date: string;
    description: string;
    description_html: string;
    epics_order: number;
    id: number;
    is_blocked: boolean;
    is_closed: boolean;
    is_voter: boolean;
    is_watcher: boolean;
    modified_date: string;
    neighbors: Neighbors;
    owner: number;
    owner_extra_info: OwnerExtraInfo;
    project: number;
    project_extra_info: ProjectExtraInfo;
    ref: number;
    status: number;
    status_extra_info: StatusExtraInfo;
    subject: string;
    tags?: ((string | null)[] | null)[] | null;
    team_requirement: boolean;
    total_voters: number;
    total_watchers: number;
    user_stories_counts: UserStoriesCounts;
    version: number;
    watchers?: (number)[] | null;
}
