import {IEpicCustomAttribute} from "./IEpicCustomAttribute";
import {IEpicStatus} from "./IEpicStatus";
import {IIssueCustomAttribute} from "./IIssueCustomAttribute";
import {IIssueStatus} from "./IIssueStatus";
import {IIssueType} from "./IIssueType";
import {IMember} from "./IMember";
import {IMilestone} from "./IMilestone";
import {IUser} from "./IUser";
import {IPoint} from "./IPoint";
import {IPriority} from "./IPriority";
import {IRole} from "./IRole";
import {ISeverity} from "./ISeverity";
import {ITaskCustomAttribute} from "./ITaskCustomAttribute";
import {ITaskStatus} from "./ITaskStatus";
import {IUserStoryCustomAttribute} from "./IUserStoryCustomAttribute";
import {IPrivateExtraInfo} from "./IPrivateExtraInfo";
import {IStatus} from "./IStatus";

export interface IProject
{
    anon_permissions?: any[] | null;
    blocked_code?: null;
    created_date: string;
    creation_template?: null;
    default_epic_status?: null;
    default_issue_status?: null;
    default_issue_type?: null;
    default_points?: null;
    default_priority?: null;
    default_severity?: null;
    default_task_status?: null;
    default_us_status?: null;
    description: string;
    epic_custom_attributes?: IEpicCustomAttribute[];
    epic_statuses?: IEpicStatus[];
    epics_csv_uuid?: null;
    i_am_admin: boolean;
    i_am_member: boolean;
    i_am_owner: boolean;
    id: number;
    is_backlog_activated: boolean;
    is_contact_activated: boolean;
    is_epics_activated: boolean;
    is_fan: boolean;
    is_featured: boolean;
    is_issues_activated: boolean;
    is_kanban_activated: boolean;
    is_looking_for_people: boolean;
    is_out_of_owner_limits: boolean;
    is_private: boolean;
    is_private_extra_info: IPrivateExtraInfo;
    is_watcher: boolean;
    is_wiki_activated: boolean;
    issue_custom_attributes?: IIssueCustomAttribute[];
    issue_statuses?: IIssueStatus[];
    issue_types?: IIssueType[];
    issues_csv_uuid?: null;
    logo_big_url: string;
    logo_small_url: string;
    looking_for_people_note: string;
    max_memberships?: null;
    members?: IMember[];
    milestones?: IMilestone[];
    modified_date: string;
    my_permissions?: (string)[] | null;
    name: string;
    notify_level: number;
    owner: IUser;
    points?: IPoint[];
    priorities?: IPriority[];
    public_permissions?: any[];
    roles?: IRole[];
    severities?: ISeverity[];
    slug: string;
    tags?: string[];
    tags_colors: {};
    task_custom_attributes?: ITaskCustomAttribute[];
    task_statuses?: ITaskStatus[];
    tasks_csv_uuid?: null;
    total_activity: number;
    total_activity_last_month: number;
    total_activity_last_week: number;
    total_activity_last_year: number;
    total_closed_milestones: number;
    total_fans: number;
    total_fans_last_month: number;
    total_fans_last_week: number;
    total_fans_last_year: number;
    total_memberships: number;
    total_milestones: number;
    total_story_points: number;
    total_watchers: number;
    totals_updated_datetime: string;
    transfer_token: string;
    us_statuses?: IStatus;
    userstories_csv_uuid?: null;
    userstory_custom_attributes?: IUserStoryCustomAttribute[];
    videoconferences?: null;
    videoconferences_extra_data?: null;
}
